# Generated by Django 4.2.20 on 2025-03-19 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_exercise_muscle_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='description_url',
            new_name='Description_URL',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='equipment',
            new_name='Equipment',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_image',
            new_name='Exercise_Image',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_image1',
            new_name='Exercise_Image1',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='exercise_name',
            new_name='Exercise_Name',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='rating',
            new_name='Rating',
        ),
    ]
