# Generated by Django 4.2.20 on 2025-03-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_rename_description_exercise_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Description_URL',
            new_name='description_url',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Equipment',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Exercise_Image',
            new_name='exercise_image',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Exercise_Image1',
            new_name='exercise_image1',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Exercise_Name',
            new_name='exercise_name',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='Rating',
            new_name='rating',
        ),
    ]
