# Generated by Django 4.2.20 on 2025-03-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(default='Default Exercise Name', max_length=200, unique=True)),
                ('description_url', models.URLField(blank=True, default='https://example.com', null=True)),
                ('exercise_image', models.URLField(blank=True, default='https://example.com/image.jpg', null=True)),
                ('exercise_image1', models.URLField(blank=True, default='https://example.com/image1.jpg', null=True)),
                ('muscle_group_details', models.URLField(blank=True, default='https://example.com/muscle-group', null=True)),
                ('muscle_group', models.CharField(default='Generic Muscle Group', max_length=100)),
                ('equipment_details', models.URLField(blank=True, default='https://example.com/equipment', null=True)),
                ('equipment', models.CharField(default='Generic Equipment', max_length=100)),
                ('rating', models.FloatField(blank=True, default=5.0, null=True)),
                ('description', models.CharField(blank=True, default='No description provided', max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='description_url',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='equipment_details',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_image',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_image1',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='exercise_name',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='muscle_group_details',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.AddField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(default='None Provided', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('weight', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.ForeignKey(default='None Provided', on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.exercisetype'),
        ),
    ]
