# Generated by Django 4.2.20 on 2025-03-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_alter_exercise_exercise_type_alter_exercise_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date_created',
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
