# Generated by Django 4.2.20 on 2025-03-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_alter_exerciseset_exercise_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='reps',
            new_name='sets',
        ),
    ]
