# Generated by Django 4.2.20 on 2025-03-21 11:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_rename_reps_set_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sets_reps',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
