# Generated by Django 4.2.20 on 2025-03-22 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0015_exercise_sets_reps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='sets',
        ),
        migrations.AddField(
            model_name='set',
            name='reps',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='set_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workouts.exercise'),
            preserve_default=False,
        ),
    ]
