# Generated by Django 4.2.20 on 2025-03-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0016_remove_set_sets_set_reps_set_set_number_set_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='sets_reps',
        ),
    ]
